classify_requirements:
  description: >
    Review the extracted requirements and classify each one according to IEEE 830 
    standards. Categorize requirements as Functional (what the system should do), 
    Non-Functional (how the system should perform), or Out-of-Scope (items that 
    fall outside the current project boundaries). Provide clear justification 
    for each classification decision.
  expected_output: >
    A structured list of all requirements with clear classification tags 
    (Functional, Non-Functional, Out-of-Scope). Each requirement should include 
    its category label and a brief rationale for the classification decision.
  agent: classifier