extract_requirements:
  description: >
    Analyze the provided unstructured text input and extract all potential 
    requirement statements. Identify actionable items, system behaviors, 
    constraints, and specifications while filtering out background information, 
    context, and non-requirement content. Transform informal language into 
    clear, structured requirement statements that can be further processed.
  expected_output: >
    A comprehensive list of extracted requirement statements, each clearly 
    articulated and actionable. Each requirement should be presented as a 
    separate item with sufficient detail for classification and implementation 
    planning.
  agent: requirement_extractor