write_srs_document:
  description: >
    Create a comprehensive Software Requirements Specification document using 
    the classified requirements. Structure the document according to IEEE 830 
    standards with sections including Introduction, Overall Description, 
    Functional Requirements, Non-Functional Requirements, and Constraints. 
    Ensure professional formatting, clear organization, and stakeholder-friendly 
    language while maintaining technical accuracy.
  expected_output: >
    A complete, well-structured SRS document in {output_format} format that 
    follows IEEE 830 standards. The document should be professionally formatted, 
    logically organized, and ready for stakeholder review and development team 
    implementation.
  agent: srs_writer